version: v1.0.0
name: App Name
port: 8081
database:
  mysql:
    enable: true
    driver: mysql
    host: 127.0.0.1
    port: 3334
    username: root
    password: root
    database: warpin
    autoReconnect: true
    startInterval: 2 #second
    maxError: 5
    timeoutConnection: 5000 #milisecond
  redis:
    enable: true
    host: 127.0.0.1
    port: 6379
    autoReconnect: true
    startInterval: 2
    maxError: 5
  mongo:
    enable: true
    host: 127.0.0.1
    port: 27017
    username: admin
    password: secret
    autoReconnect: true
    startInterval: 2 #second
    maxError: 5
    timeoutConnection: 5000 #milisecond